### ISSUE TITLE
 Very slow drawing speeds on cards with a large amount of content offscreen

### ISSUE THREAD

**Issue by orangelover12** [Rytisgit/Anki-StylusDraw#10]
First of all, I would like to say that I am really enjoying using the addon and thank you very much.
I am using this addon every day and I found one error.
For some cards that contain large photos or a lot of text, the speed is extremely slow. If possible, could you please correct the error? thank you

**Comment by Rytisgit** [comment]
As rin-w said, first could you confirm that you have tried to enable hardware acceleration. For QT6 the method is running a cmd command `echo auto > %APPDATA%\Anki2\gldriver6` https://github.com/Rytisgit/Anki-StylusDraw/raw/master/docs/qt6fast.png 

for QT5 the method is selecting a different option from the settings menu of the video driver: https://github.com/Rytisgit/Anki-StylusDraw/raw/master/docs/dontUseSoftwareRendering.png

You will need to restart Anki after both.

You can also do a quick test of trying the drawing on the standalone website here: https://rytisgit.github.io/Anki-StylusDraw/ , since browsers have hardware acceleration by default these days, and see if the drawing is still slow.

**Comment by orangelover12** [comment]
Thank you for answer.
I am currently using version 2.1.65, QT6 of anki on my laptop, and I have enabled hardware acceleration.
I took the advice and tried it on my desktop at home and found that it worked properly. 
It seems to be a hardware problem with my laptop.

 Thank you both so much for your answers. 
I wish you all the best!

**Comment by Rytisgit** [comment]
It was not clear initially what your problem was, but I have understood it now. I added a follow screen mode and small canvas mode, so that drawing speed is not influenced by the size of the card making the canvas very big offscreen. you can try it out by downloading the newest version and toggling either of the modes using these options:https://raw.githubusercontent.com/Rytisgit/Anki-StylusDraw/master/docs/followScreenOnBigCards.png

**Comment by orangelover12** [comment]
I just finished updating the addon. This update is much better than I hoped for. Using a smaller canvas eliminated all the problems I had before. Thank you so much for including this amazing feature. I wish you all the best!
